defaults:
  - cluster/local

hydra:
  run:
    dir: results/${name}_${dacbench_sgd_config.dataset_name}
  sweep:
    dir: results/${name}_${dacbench_sgd_config.dataset_name}
  job:
    chdir: true

name: Adam_fixed_benchmark
seeds: [1]
agent:
  type: StaticAgent
  lr: 0.001
num_episodes: 1
optimizer_type: adam

dacbench_sgd_config:
  epoch_mode: False
  cutoff: 100
  dataset_name: CIFAR10
  torch_hub_model: ['pytorch/vision:v0.10.0', 'resnet18', False]