defaults:
  - base

name: Adam_fixed_cifar100
agent:
  type: StaticAgent
  lr: 0.001
num_episodes: 1
optimizer_type: adam

dacbench_sgd_config:
  cutoff: 3
  dataset_name: CIFAR100
  torch_hub_model: ["chenyaofo/pytorch-cifar-models", "cifar100_resnet20", False]