defaults:
  - base

name: Adam_fixed_cifar100
agent:
  type: StaticAgent
  lr: 0.001
num_episodes: 1
optimizer_type: adam

dacbench_sgd_config:
  cutoff: 300
  dataset_name: CIFAR100
  fraction_of_dataset: 1.0
  torch_hub_model: ["chenyaofo_pytorch-cifar-models_master", "cifar100_resnet20", False]