defaults:
  - base

name: Adam_fixed_cifar10
agent:
  type: StaticAgent
  lr: 0.001
num_episodes: 1
optimizer_type: adam

hydra:
  launcher:
    timeout_min: 4500

dacbench_sgd_config:
  cutoff: 300
  dataset_name: CIFAR10
  fraction_of_dataset: 1.0
  custom_model: wrn16-8