defaults:
  - base

name: Adam_fixed_libsvm/${dacbench_sgd_config.dataset_name}
agent:
  type: StaticAgent
  lr: 0.001
num_episodes: 1
optimizer_type: adam

  #hydra:
  #launcher:
  #  timeout_min: 120
  #  cpus_per_task: 4
  #  mem_gb: 6

dacbench_sgd_config:
  cutoff: 100
  dataset_name: iris
  fraction_of_dataset: 1.0
  custom_model: logistic_reg_${dacbench_sgd_config.dataset_name}