defaults:
  - override hydra/launcher: submitit_slurm

name: Adam_fixed_roberta_bookwiki
seed: 1
optimizer:
  type: adam
  lr: 0.001
  weight_decay: 0.01

# TODO needs to be adjusted
hydra:
  launcher:
    timeout_min: 4320
    cpus_per_task: 4
    gres: "gpu:4"
    mem_gb: 256
    nodes: 1
    ntasks_per_node: 8  