defaults:
  - cluster/cpu

hydra:
  run:
    dir: results/${name}
  sweep:
    dir: results/${name}
  job:
    chdir: true

name: base
seed: 0
dacbench_sgd_config:
  dataset_name: dataset
  instance_set_path: ../../../../../instance_sets/sgd/sgd_train_100instances.csv