defaults:
  - base

name: CAWR_libsvm/${dacbench_sgd_config.dataset_name}
agent:
  type: CosineAnnealingWRAgent
  T_0: 10
  eta_min: 0
  base_lr: 0.005
  t_mult: 2
num_episodes: 1
optimizer_type: adam

hydra:
  launcher:
    timeout_min: 120
    cpus_per_task: 4
    mem_gb: 6

libsvm:
  wine: 300
  vowel: 900
  vehicle: 1400
  pendigits: 11800
  letter: 23500
  dna: 3200
  sensorless: 91500
  iris: 300
  aloi: 168800

dacbench_sgd_config:
  epoch_mode: False # in SGDWR paper lr is adapted every mini batch
  cutoff: ${libsvm.${dacbench_sgd_config.dataset_name}} # 50000*0.8=40000 -> 40000/64 = 625 -> 100 epochs = 100*625=187500
  dataset_name: aloi
  fraction_of_dataset: 1.0
  custom_model: logistic_reg_${dacbench_sgd_config.dataset_name}