defaults:
  - base

name: CAWR_mnist
agent:
  type: CosineAnnealingWRAgent
  T_0: 10
  eta_min: 0
  base_lr: 0.05
  t_mult: 2
num_episodes: 1
optimizer_type: adam

hydra:
  launcher:
    timeout_min: 1200

dacbench_sgd_config:
  epoch_mode: False # in SGDWR paper lr is adapted every mini batch 
  cutoff: 13500 # 60000*0.6*0.8=28800 -> 28800/64 = 450 -> 30 episodes = 30*450=13500
  dataset_name: MNIST