defaults:
  - base

name: CAWR_cifar10
agent:
  type: CosineAnnealingWRAgent
  T_0: 10
  eta_min: 0
  base_lr: 0.005
  t_mult: 2
num_episodes: 1
optimizer_type: adam

hydra:
  launcher:
    timeout_min: 8000

dacbench_sgd_config:
  epoch_mode: False # in SGDWR paper lr is adapted every mini batch
  cutoff: 187500 # 50000*0.8=40000 -> 40000/64 = 625 -> 300 epochs = 300*625=187500
  dataset_name: CIFAR10
  fraction_of_dataset: 1.0
  custom_model: wrn16-8