defaults:
  - base

name: COCOB_benchmark
agent:
  type: StaticAgent
  lr: 1
num_episodes: 1
optimizer_type: COCOB_trackable

dacbench_sgd_config:
  optimizer_params: null
  cutoff: 2
  dataset_name: MNIST