defaults:
  - cluster/local

hydra:
  run:
    dir: results/${name}_${dacbench_sgd_config.dataset_name}
  sweep:
    dir: results/${name}_${dacbench_sgd_config.dataset_name}
  job:
    chdir: true

name: COCOB_test
seeds: [1]
agent:
  type: StaticAgent
  lr: 1
num_episodes: 1
optimizer_type: COCOB_trackable
track_effective_lr: True

dacbench_sgd_config:
  optimizer_params: null
  epoch_mode: False
  cutoff: 100
  dataset_name: CIFAR10