defaults:
  - base

name: COCOB_fmnist
agent:
  type: StaticAgent
  lr: 1
num_episodes: 1
optimizer_type: COCOB_trackable
track_effective_lr: true

dacbench_sgd_config:
  optimizer_params: null
  cutoff: 30
  fraction_of_dataset: 1.0
  dataset_name: FashionMNIST