defaults:
  - base

name: COCOB_cifar10
agent:
  type: StaticAgent
  lr: 1
num_episodes: 1
optimizer_type: COCOB_trackable
track_effective_lr: true

dacbench_sgd_config:
  optimizer_params: null
  cutoff: 30
  dataset_name: CIFAR10
  torch_hub_model: ["chenyaofo/pytorch-cifar-models", "cifar10_resnet20", False]