defaults:
  - base

name: COCOB_cifar100
agent:
  type: StaticAgent
  lr: 1
num_episodes: 1
optimizer_type: COCOB_trackable
track_effective_lr: true

dacbench_sgd_config:
  optimizer_params: null
  cutoff: 50
  dataset_name: CIFAR100
  torch_hub_model: ["chenyaofo_pytorch-cifar-models_master", "cifar100_resnet20", False]