defaults:
  - base

name: COCOB_cifar100
agent:
  type: StaticAgent
  lr: 1
num_episodes: 1
optimizer_type: COCOB_trackable
track_effective_lr: true

hydra:
  launcher:
    timeout_min: 6000

dacbench_sgd_config:
  optimizer_params: null
  cutoff: 300
  dataset_name: CIFAR100
  fraction_of_dataset: 1.0
  custom_model: densenet121