defaults:
  - _self_
  - cluster/local
  - override hydra/sweeper: SMAC

seed: 42
name: smacpolicy_cifar10_${seed}

dacbench_sgd_config:
    cutoff: 30
    seed: ${seed}
    epoch_mode: true
    use_validation: false
    use_testing: false
    num_episodes: 1
    dataset_name: CIFAR10
    fraction_of_dataset: 1.0
    torch_hub_model: ["chenyaofo_pytorch-cifar-models_master", "cifar10_resnet20", False]
    instance_set_path: ../../instance_sets/sgd/sgd_train_100instances.csv

hydra:
  sweeper:
    smac_class: smac.facade.algorithm_configuration_facade.AlgorithmConfigurationFacade
    scenario:
      seed: ${seed}
      n_trials: 500
      deterministic: true
      n_workers: 64
    smac_kwargs:
      dask_client:
        _target_: dask.distributed.Client
        address: ${create_cluster:${cluster},${hydra.sweeper.scenario.n_workers}}
      logging_level: 20  # 10 DEBUG, 20 INFO
    search_space:  # TODO adjust search space
      hyperparameters:
        x0:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x1:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x2:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x3:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x4:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x5:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x6:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x7:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x8:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x9:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x10:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x11:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x12:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x13:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x14:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x15:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x16:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x17:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x18:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x19:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x20:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x21:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x22:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x23:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x24:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x25:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x26:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x27:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x28:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
        x29:
          type: uniform_float
          lower: 0
          upper: 0.005
          log: false
  run:
    dir: results/smacpolicy_cifar10_${seed}
  sweep:
    dir: results/smacpolicy_cifar10_${seed}
  job:
    chdir: true

x0: 0.0025
x1: 0.0025
x2: 0.0025
x3: 0.0025
x4: 0.0025
x5: 0.0025
x6: 0.0025
x7: 0.0025
x8: 0.0025
x9: 0.0025
x10: 0.0025
x11: 0.0025
x12: 0.0025
x13: 0.0025
x14: 0.0025
x15: 0.0025
x16: 0.0025
x17: 0.0025
x18: 0.0025
x19: 0.0025
x20: 0.0025
x21: 0.0025
x22: 0.0025
x23: 0.0025
x24: 0.0025
x25: 0.0025
x26: 0.0025
x27: 0.0025
x28: 0.0025
x29: 0.0025
