defaults:
  - base

name: dadaptation_libsvm/${dacbench_sgd_config.dataset_name}
agent:
  type: StaticAgent
  lr: 1
num_episodes: 1
optimizer_type: DAdaptAdam
track_effective_lr: true
track_dlr: true

hydra:
  launcher:
    timeout_min: 120
    cpus_per_task: 4
    mem_gb: 6

dacbench_sgd_config:
  optimizer_params:
    weight_decay: 0
  cutoff: 100
  fraction_of_dataset: 1.0
  dataset_name: iris
  custom_model: logistic_reg_${dacbench_sgd_config.dataset_name}