defaults:
  - base

name: DoWG_fashion_mnist
agent:
  type: StaticAgent
  lr: 1
num_episodes: 1
optimizer_type: dowg

dacbench_sgd_config:
  optimizer_params: null
  cutoff: 30
  fraction_of_dataset: 1.0
  dataset_name: FashionMNIST