defaults:
  - base

name: DoWG_cifar10
agent:
  type: StaticAgent
  lr: 1
num_episodes: 1
optimizer_type: dowg
track_effective_lr: true

hydra:
  launcher:
    timeout_min: 4500

dacbench_sgd_config:
  optimizer_params: null
  cutoff: 300
  dataset_name: CIFAR10
  fraction_of_dataset: 1.0
  custom_model: wrn16-8