defaults:
  - base

name: DoWG_mnist
agent:
  type: StaticAgent
  lr: 1
num_episodes: 1
optimizer_type: dowg
track_effective_lr: true

dacbench_sgd_config:
  optimizer_params: null
  cutoff: 5
  fraction_of_dataset: 1.0
  dataset_name: MNIST