defaults:
  - base

name: DoWG_dtd
agent:
  type: StaticAgent
  lr: 1
num_episodes: 1
optimizer_type: dowg
track_effective_lr: true

dacbench_sgd_config:
  optimizer_params: null
  cutoff: 300
  device: cuda
  dataset_name: DTD
  fraction_of_dataset: 1.0
  custom_model: vit_tiny_patch16_224

hydra:
  launcher:
    partition: null
    timeout_min: 300
    gres: "gpu:1"
    nodes: 1
    mem_gb: 16