defaults:
  - base

name: SMAC_fixed_cifar10
optimizer_type: adam
num_episodes: 1

smac:
  optimizer_type: adam
  n_trials: 50
  lr_min: 0
  lr_max: 0.01
  lr_default: 0.001
  dacbench_sgd_config:
    cutoff: 1
    dataset_name: CIFAR10
    instance_set_path: ../../../../../instance_sets/sgd/sgd_train_100instances.csv
    torch_hub_model: ["chenyaofo_pytorch-cifar-models_master", "cifar10_resnet20", False]

dacbench_sgd_config:
  cutoff: 50
  dataset_name: CIFAR10
  torch_hub_model: ["chenyaofo_pytorch-cifar-models_master", "cifar10_resnet20", False]