defaults:
  - base

name: tuned_smacfixed_dtd
optimizer_type: adam
agent:
  type: StaticAgent
  lr: 0.000880923938 
num_episodes: 1

dacbench_sgd_config:
  cutoff: 300
  device: cuda
  dataset_name: DTD
  fraction_of_dataset: 1.0
  custom_model: vit_tiny_patch16_224

hydra:
  launcher:
    partition: null
    timeout_min: 300
    gres: "gpu:1"
    nodes: 1
    mem_gb: 16
