defaults:
  - base
  - override hydra/sweeper: HyperSMAC
  - override hydra/launcher: submitit_slurm

libsvm:
  wine: 300
  vowel: 900
  vehicle: 1400
  pendigits: 11800
  letter: 23500
  dna: 3200
  sensorless: 91500
  iris: 300
  aloi: 168800

hydra:
  sweeper:
    n_trials: 50
    budget_variable: cutoff
    sweeper_kwargs:
      optimizer_kwargs:
        smac_facade: 
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade
          _partial_: true
        intensifier: 
          _target_: smac.intensifier.hyperband.Hyperband
          _partial_: true
        scenario:
          n_trials: ${hydra.sweeper.n_trials}
          seed: ${seed}
          min_budget: 20
          max_budget: ${libsvm.${dacbench_sgd_config.dataset_name}}
          deterministic: true
          n_workers: 1
          output_directory: ${hydra.sweep.dir}
    search_space:
      hyperparameters:
        T0:
          type: uniform_int
          lower: 0
          upper: 50
          default: 10
          log: false
        eta_min:
          type: uniform_float
          lower: 0
          upper: 0.005
          default: 0
          log: false
        base_lr:
          type: uniform_float
          lower: 0
          upper: 1
          default: 0.005
          log: false
        t_mult:
          type: uniform_int
          lower: 1
          upper: 5
          default: 2
          log: false
  run:
    dir: results/${name}
  sweep:
    dir: results/${name}
  job:
    chdir: true
  launcher:
    timeout_min: 240
    nodes: 1
    partition: ai
    gres: null
    cpus_per_task: 4
    tasks_per_node: 1
    mem_gb: 8

T0: 10
eta_min: 0
base_lr: 0.0025
t_mult: 2
cutoff: 300

name: tune_CAWR_libsvm/${dacbench_sgd_config.dataset_name}
agent:
  type: CosineAnnealingWRAgent
  T_0: 10
  eta_min: 0
  base_lr: 0.005
  t_mult: 2
num_episodes: 1
optimizer_type: adam

dacbench_sgd_config:
  seed: ${seed}
  epoch_mode: False # in SGDWR paper lr is adapted every mini batch
  use_validation: false
  use_testing: false
  use_validation_as_test: True
  cutoff: ${cutoff}
  dataset_name: aloi
  fraction_of_dataset: 1.0
  custom_model: logistic_reg_${dacbench_sgd_config.dataset_name}