defaults:
  - base

name: tuned_cawr_libsvm/${dacbench_sgd_config.dataset_name}
agent:
  type: CosineAnnealingWRAgent
  T_0: ${libsvm.${dacbench_sgd_config.dataset_name}.T0}
  eta_min: ${libsvm.${dacbench_sgd_config.dataset_name}.eta_min}
  base_lr: ${libsvm.${dacbench_sgd_config.dataset_name}.base_lr}
  t_mult: ${libsvm.${dacbench_sgd_config.dataset_name}.t_mult}
num_episodes: 1
optimizer_type: adam

hydra:
  launcher:
    timeout_min: 120
    cpus_per_task: 4
    mem_gb: 6

libsvm:
  wine:
    cutoff: 300
    T0: 30
    base_lr: 0.2405267676853
    eta_min: 0.0043424324019
    t_mult: 4
  vowel:
    cutoff: 900
    T0: 45
    base_lr: 0.0179811789472
    eta_min: 0.0011440533481
    t_mult: 5
  vehicle:
    cutoff: 1400
    T0: 45
    base_lr: 0.0179811789472
    eta_min: 0.0011440533481
    t_mult: 5
  pendigits:
    cutoff: 11800
    T0: 38
    base_lr: 0.598658484197
    eta_min: 0.0030055750587
    t_mult: 2
  letter:
    cutoff: 23500
    T0: 38
    base_lr: 0.598658484197
    eta_min: 0.0030055750587
    t_mult: 2
  dna:
    cutoff: 3200
    T0: 38
    base_lr: 0.598658484197
    eta_min: 0.0030055750587
    t_mult: 2
  sensorless:
    cutoff: 91500
    T0: 38
    base_lr: 0.598658484197
    eta_min: 0.0030055750587
    t_mult: 2
  iris:
    cutoff: 300
    T0: 30
    base_lr: 0.2405267676853
    eta_min: 0.0043424324019
    t_mult: 4
  aloi:
    cutoff: 168800
    T0: 38
    base_lr: 0.598658484197
    eta_min: 0.0030055750587
    t_mult: 2

dacbench_sgd_config:
  seed: ${seed}
  epoch_mode: False # in SGDWR paper lr is adapted every mini batch
  cutoff: ${libsvm.${dacbench_sgd_config.dataset_name}.cutoff}
  dataset_name: aloi
  fraction_of_dataset: 1.0
  custom_model: logistic_reg_${dacbench_sgd_config.dataset_name}