defaults:
  - base

name: tuned_smacfixed_libsvm/${dacbench_sgd_config.dataset_name}
agent:
  type: StaticAgent
  lr: ${libsvm.${dacbench_sgd_config.dataset_name}}
num_episodes: 1
optimizer_type: adam

hydra:
  launcher:
    timeout_min: 120
    cpus_per_task: 4
    mem_gb: 6

libsvm:
  wine: 0.9998564629315
  vowel: 0.9998439822168
  vehicle: 0.7319939418114
  pendigits: 0.7535255294272
  letter: 0.7044118702946
  dna: 0.9522964199496
  sensorless: 0.6970762748657
  iris: 0.9988558724108
  aloi: 0.2709798509559

dacbench_sgd_config:
  epoch_mode: True
  cutoff: 100 
  dataset_name: aloi
  fraction_of_dataset: 1.0
  custom_model: logistic_reg_${dacbench_sgd_config.dataset_name}