# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm
  
hydra:
  launcher:
    name: ${name}
    partition: ai
    nodes: 1
    cpus_per_task: 16
    gres: null
    timeout_min: 360
    mem_gb: 16