# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm
  
hydra:
  launcher:
    name: ${name}
    partition: ai
    nodes: 1
    cpus_per_task: 40
    gres: null
    timeout_min: 1200
    mem_gb: 140
