defaults:
  - __self__

dacbench_sgd_config:
  cutoff: 300
  device: cuda
  dataset_name: DTD
  fraction_of_dataset: 1.0
  custom_model: vit_tiny_patch16_224

hydra:
  launcher:
    partition: null
    timeout_min: 300